export enum Role {
  AGRICULTEUR = 'AGRICULTEUR',
  TECHNICIEN = 'TECHNICIEN',
  ADMIN = 'ADMIN',
}

export enum DeviceStatus {
  ACTIVE = 'ACTIVE',
  OFFLINE = 'OFFLINE',
  MAINTENANCE = 'MAINTENANCE',
  DISABLED = 'DISABLED',
}

export enum AlertLevel {
  INFO = 'INFO',
  WARNING = 'WARNING',
  CRITICAL = 'CRITICAL',
}

export enum AlertType {
  MILDIOU_RISK = 'MILDIOU_RISK',
  OIDIUM_RISK = 'OIDIUM_RISK',
  HYDRIC_STRESS = 'HYDRIC_STRESS',
  HUMIDITE_EXCESSIVE = 'HUMIDITE_EXCESSIVE',
  TEMPERATURE_CRITIQUE = 'TEMPERATURE_CRITIQUE',
  PH_ANORMAL = 'PH_ANORMAL',
  LUMINOSITE_ANORMALE = 'LUMINOSITE_ANORMALE',
  DEVICE_OFFLINE = 'DEVICE_OFFLINE',
  CUSTOM = 'CUSTOM',
}

export enum SubscriptionPlan {
  STANDARD = 'STANDARD',
  PRO = 'PRO',
  PREMIUM = 'PREMIUM',
}
