version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: phytera_postgres
    restart: always
    environment:
      POSTGRES_USER: phytera_user
      POSTGRES_PASSWORD: phytera_password
      POSTGRES_DB: phytera_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: phytera_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
